CREATE DATABASE COMPANYA3;

USE COMPANYA3;

CREATE TABLE EMPLOYEE
(
EID INT PRIMARY KEY,
ENMAE VARCHAR(30),
AGE INT,
SALARY DECIMAL(10,2)

);


INSERT INTO EMPLOYEE VALUE(1,'NITHIN',19,'45000');

INSERT INTO EMPLOYEE VALUE(2,'KRISHNA',19,'55000');
INSERT INTO EMPLOYEE VALUE(3,'YASH',21,'65000');
INSERT INTO EMPLOYEE VALUE(4,'MOHI',19,'45000');
INSERT INTO EMPLOYEE VALUE(5,'BAL',20,'55000');

SELECT *FROM EMPLOYEE;


SELECT COUNT(ENMAE) AS EMPCOUNT FROM EMPLOYEE;
SELECT SUM(SALARY) AS SUMSAL FROM EMPLOYEE;

SELECT ENMAE,SALARY
FROM EMPLOYEE
ORDER BY SALARY DESC;


select salary ,count(*)
as empcount
from employee
group by salary;