CREATE DATABASE COMPANY4;


USE COMPANY4;

CREATE TABLE Customers(

ID INT PRIMARY KEY auto_increment,
CNAME VARCHAR(30),
AGE INT,
ADDRESS VARCHAR(30),
SALARY DECIMAL(10,2)


);

INSERT INTO CUSTOMERS (CNAME,AGE,ADDRESS,SALARY)
VALUES('NITHIN ',19,'MYSORE','45000.6')
;


	
	DELIMITER //

CREATE TRIGGER AFTER_INSERT_SALARY
AFTER INSERT ON CUSTOMERS 
FOR EACH ROW 
BEGIN 
    SET @my_sal_diff = concat('salary insert is: ', NEW.SALARY);
END;
//

DELIMITER ;

INSERT INTO CUSTOMERS (CNAME,AGE,ADDRESS,SALARY)
VALUES('NYASH ',19,'MYSORE','55000.6')
;

SELECT @my_sal_diff as saldiff;


 
 DELIMITER //
CREATE TRIGGER AFTER_UPDATE_SALARY
AFTER UPDATE ON CUSTOMERS
FOR EACH ROW
BEGIN
    DECLARE old_salary DECIMAL(10,2);
    DECLARE new_salary DECIMAL(10,2);    
    SET old_salary = OLD.SALARY;
    SET new_salary = NEW.SALARY;    
    SET @my_sal_diff = CONCAT('SALARY DIFFERENCE IS: ', new_salary - old_salary);
END; 
//
UPDATE CUSTOMERS SET SALARY='90000' WHERE ID=1;
SELECT @my_sal_diff as saldiss;

DELIMITER ;


DELIMITER //

CREATE TRIGGER AFTER_DELETE_SALARY
AFTER DELETE ON CUSTOMERS
FOR EACH ROW
BEGIN
    SET @deleted_salary_info = CONCAT('Deleted salary is: ', OLD.SALARY);
END;
//

DELIMITER ;

delete from customers where ID=1;
SELECT @deleted_salary_info AS DELSAL;




DESC CUSTOMERS;